### ISSUE TITLE
Timeline and definition of related terms

### ISSUE THREAD

**Issue by fdegir** [cdfoundation/glossary#7]
Would it make sense to add timeline and definitions of related terms given that some of those terms generally go together with CI and CD or referred as part of the conversations. Some of these that come to my mind are
- DevOps
- DevSecOps
- GitOps
- Progressive Delivery

**Comment by salaboy** [comment]
MLOps as well?

**Comment by tracymiranda** [comment]
Yes to all of those. I think it makes sense to add them in there and we can always reorganize the document if it starts getting too cluttered.

**Comment by fdegir** [comment]
Thanks Tracy.

Sent first PR, adding DevOps: https://github.com/cdfoundation/glossary/pull/8

Closing the issue to keep the backlog clean.
